services:
  app:
    image: ghcr.io/splrge/traefik:latest
    ports: 
      - 80:80
      - 443:443
      - 3333:3333
    volumes:
      - ./data:/app/tmp/database
    environment:
      TZ: UTC
      PORT: 3333
      HOST: 0.0.0.0
      APP_URL: http://localhost # Must be setted for Microsoft authentication 
      LOG_LEVEL: info
      APP_KEY: # Generate a key with docker run --rm ghcr.io/splrge/traefik node ace generate:key
      NODE_ENV: production
      SESSION_DRIVER: cookie
      MICROSOFT_CLIENT_ID: # Optional 
      MICROSOFT_CLIENT_SECRET: # Optional 